fix: work around static linking error in tests

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -29,16 +29,12 @@ jobs:
               - x86_64-unknown-linux-gnu
             build: |
               cargo build --target x86_64-unknown-linux-gnu --release
-            test: | # avoid the problems in: https://github.com/rust-lang/rust/issues/78210
-              cargo test --target x86_64-unknown-linux-gnu --release || { echo "Unit tests failed" >&2; exit 1; }
 
           - os: ubuntu-24.04-arm # -latest not yet available
             targets:
               - aarch64-unknown-linux-gnu
             build: |
               cargo build --target aarch64-unknown-linux-gnu --release
-            test: | # avoid the problems in: https://github.com/rust-lang/rust/issues/78210
-              cargo test --target aarch64-unknown-linux-gnu --release || { echo "Unit tests failed" >&2; exit 1; }
 
           - os: macos-latest
             targets:
@@ -47,8 +43,6 @@ jobs:
             build: |
               cargo build --target x86_64-apple-darwin --release
               cargo build --target aarch64-apple-darwin --release
-            test: |
-              cargo test --release || { echo "Unit tests failed" >&2; exit 1; }
 
           - os: windows-latest
             targets:
@@ -57,8 +51,6 @@ jobs:
             build: |
               cargo build --target x86_64-pc-windows-msvc --release
               cargo build --target aarch64-pc-windows-msvc --release
-            test: |
-              cargo test --release || { echo "Unit tests failed" >&2; exit 1; }
 
     steps:
       - name: Checkout repo
@@ -102,8 +94,11 @@ jobs:
         run: ${{ matrix.build }}
 
       - name: Run tests
+        env:
+          RUSTFLAGS: > # avoid the problems in: https://github.com/rust-lang/rust/issues/78210
+            ${{ startsWith(matrix.os, 'ubuntu') && '"-C target-feature=-crt-static"' || '"-C target-feature=+crt-static"' }}
         run: |
-          ${{ matrix.test }}
+          cargo test --release || { echo "Unit tests failed" >&2; exit 1; }
 
           test_stdout="$(cargo run --quiet --release -- --test)"
           exit_code=$?
